services:
  ###
  ### Postgres shards
  ###
  postgres-1:
    image: postgres:18-alpine
    container_name: tl-postgres-1
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL_1}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_1}:5432"
    volumes:
      - db_data_1:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres-2:
    image: postgres:18-alpine
    container_name: tl-postgres-2
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL_2}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_2}:5432"
    volumes:
      - db_data_2:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  ###
  ### Migrations
  ###
  migrate-1:
    image: migrate/migrate:4
    container_name: tl-migrate-1
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-1:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "${DATABASE_URL_1}", "up"]

  migrate-2:
    image: migrate/migrate:4
    container_name: tl-migrate-2
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-2:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "${DATABASE_URL_2}", "up"]

  ###
  ### Redpanda
  ###
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.4
    container_name: tl-redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1 # n cores
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
      - --set redpanda.auto_create_topics_enabled=true
      - --set redpanda.default_topic_partitions=64
    ports:
      - "9092:9092"

  console:
    image: docker.redpanda.com/redpandadata/console:v3.3.2
    container_name: tl-redpanda-console
    environment:
      KAFKA_BROKERS: "redpanda:29092"
      CONFIG_FILEPATH: "/etc/redpanda/console.yaml"
    ports:
      - "9090:8080"
    volumes:
      - ./console-config.yaml:/etc/redpanda/console.yaml:ro
      - ./proto:/app/proto:ro

  ###
  ### API Service
  ###
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: tl-api-1
    restart: unless-stopped
    environment:
      NUM_SHARDS: 2
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKERS: "redpanda:29092"
    ports:
      - "6061:6060"
    depends_on:
      postgres-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-2:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: tl-api-2
    restart: unless-stopped
    environment:
      NUM_SHARDS: 2
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKERS: "redpanda:29092"
    ports:
      - "6062:6060"
    depends_on:
      postgres-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ###
  ### Nginx
  ###
  nginx:
    image: nginx:alpine
    container_name: tl-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api-1:
        condition: service_healthy
      api-2:
        condition: service_healthy

  ###
  ### Workers
  ###
  worker-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    container_name: tl-worker-1
    restart: unless-stopped
    command: ["--partitions=0-31"]
    environment:
      DATABASE_URL: ${DATABASE_URL_1}
      KAFKA_BROKERS: "redpanda:29092"
    ports:
      - "7071:6060"
    depends_on:
      migrate-1:
        condition: service_completed_successfully
      migrate-2:
        condition: service_completed_successfully

  worker-2:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    container_name: tl-worker-2
    restart: unless-stopped
    command: ["--partitions=32-63"]
    environment:
      DATABASE_URL: ${DATABASE_URL_2}
      KAFKA_BROKERS: "redpanda:29092"
    ports:
      - "7072:6060"
    depends_on:
      migrate-1:
        condition: service_completed_successfully
      migrate-2:
        condition: service_completed_successfully

volumes:
  db_data_1:
  db_data_2:
