services:
  ###
  ### Postgres shards
  ###
  postgres-s1:
    image: postgres:18-alpine
    container_name: tl-postgres-s1
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL_S1}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_S1}:5432"
    volumes:
      - db_data_s1:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres-s2:
    image: postgres:18-alpine
    container_name: tl-postgres-s2
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL_S2}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_S2}:5432"
    volumes:
      - db_data_s2:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

  ###
  ### Migrations
  ###
  migrate-s1:
    image: migrate/migrate:4
    container_name: tl-migrate-s1
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-s1:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "${DATABASE_URL_S1}", "up"]

  migrate-s2:
    image: migrate/migrate:4
    container_name: tl-migrate-s2
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-s2:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "${DATABASE_URL_S2}", "up"]

  ###
  ### Redpanda
  ###
  redpanda:
    profiles: ["broker"]
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.4
    container_name: tl-redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1 # n cores
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
    ports:
      - "9092:9092"

  console:
    profiles: ["broker"]
    image: docker.redpanda.com/redpandadata/console:v3.3.2
    container_name: tl-redpanda-console
    environment:
      KAFKA_BROKERS: "redpanda:29092"
      CONFIG_FILEPATH: "/etc/redpanda/console.yaml"
    ports:
      - "9090:8080"
    volumes:
      - ./console-config.yaml:/etc/redpanda/console.yaml:ro
      - ./proto:/app/proto:ro

  ###
  ### API Service
  ###
  api-s1:
    profiles: ["api"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tl-api-s1
    restart: unless-stopped
    environment:
      DATABASE_URL_S1: ${DATABASE_URL_S1}
      DATABASE_URL_S2: ${DATABASE_URL_S2}
      KAFKA_BROKERS: "redpanda:29092"
    depends_on:
      postgres-s1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  api-s2:
    profiles: ["api"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tl-api-s2
    restart: unless-stopped
    environment:
      DATABASE_URL_S1: ${DATABASE_URL_S1}
      DATABASE_URL_S2: ${DATABASE_URL_S2}
      KAFKA_BROKERS: "redpanda:29092"
    depends_on:
      postgres-s2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ###
  ### Nginx
  ###
  nginx:
    profiles: ["api"]
    image: nginx:alpine
    container_name: tl-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api-s1:
        condition: service_healthy
      api-s2:
        condition: service_healthy

volumes:
  db_data_s1:
  db_data_s2:
