global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'apis'
    static_configs:
      - targets: ['api-1:8080', 'api-2:8080']
  - job_name: 'workers'
    static_configs:
      - targets: ['worker-1:8080', 'worker-2:8080']
